version: "3.8"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                #- APP_ENV=${APP_ENV}
                - APP_ENV=local
        environment:
            #- APP_ENV=${APP_ENV}
            - APP_ENV=local
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
            - redis

    # PHP Service
    websocket:
        build:
            context: .
            target: php
            args:
                #- APP_ENV=${APP_ENV}
                - APP_ENV=local
        environment:
            #- APP_ENV=${APP_ENV}
            - APP_ENV=local
            - CONTAINER_ROLE=websocket
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 6001:6001
        depends_on:
            - database
            - redis

    # Database Server
    database:
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            #- MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_DATABASE=chatapp
            #- MYSQL_USER=${DB_USERNAME}
            - MYSQL_USER=root
            #- MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=secret
            #- MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - db-data:/var/lib/mysql

    # Redis Server
    redis:
        image: redis:alpine
        #command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        command: redis-server --appendonly yes --requirepass  "yourpassword"
        ports:
            - 6379:6379

    # Queue Server
    queue:
        build:
            context: .
            target: php
            args:
                #- APP_ENV=${APP_ENV}
                - APP_ENV=local
        environment:
            #- APP_ENV=${APP_ENV}
            - APP_ENV=local
            - CONTAINER_ROLE=queue
        working_dir: /var/www
        volumes:
            - ./:/var/www

    # Node Server
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

volumes:
    db-data: ~
